version: '2'

services:
  data:
    image: busybox
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
      - ./public:/usr/share/nginx/html
  nginx:
    image: nginx
    ports: 
      - "8080:80"
    links:
      - phpfpm
    volumes_from:
      - data
  phpfpm:
    build: ./php
    ports:
      - "9000:9000"
    volumes_from:
      - data
    environment: 
      XDEBUG_PORT: "${XDEBUG_PORT}"
    extra_hosts:
      docker_host: "${HOST_IP}"
